
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * if the user selects 'add connection' on the vmdata form
 * this form is then called to allow the user to select a subnet to connect to
 * @author Adam
 */
public class addConnection extends javax.swing.JFrame {

    /**
     * Creates new form addConnection
     */
    int index, port;
    //EZLists correspond to the hublist, I must've been really tired when I wrote this
    private ArrayList<Integer> EZSubnet = new ArrayList<>();
    private ArrayList<Integer> EZIndex = new ArrayList<>();
    
    
    public addConnection( int x, int y) {
        index = x;
        port = y; 
        //this form pops up where the vmdata form that called it was
        this.setLocation(NetworkReader.p);
        this.setUndecorated(true);
        initComponents();
        listHubs();  
    }
    //lists the hubs on the network the vm is currently not connected to
    public void listHubs(){
        for ( hub hub : NetworkReader.hubList ){
            if ( !NetworkReader.vmList.get(index).subnetList.contains(hub.getSubnet()) 
                   && ( hub.getSubnetFull() != null )){
                list1.add(hub.getName() + "@subnet: " +hub.getSubnetFull());
                EZSubnet.add(hub.getSubnet());
                EZIndex.add(hub.getIndex());
                nextButton.setEnabled(true);
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        list1 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        nextButton.setText("Next");
        nextButton.setEnabled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Hub to connect to, then select next.");

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        list1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                list1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(nextButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        VMdata s = new VMdata(index);
        s.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (list1.getSelectedIndex() != -1){
            int i = list1.getSelectedIndex();
            addConnectionFinal s = new addConnectionFinal( EZSubnet.get(list1.getSelectedIndex()), index, port, EZIndex.get(list1.getSelectedIndex()));
            //okay, this is terrible and im so sorry.  this passes a subnet, vm index, port, and hub index to the next form
            s.setVisible(true);
            super.dispose();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void list1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_list1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_list1PropertyChange
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel jLabel1;
    private java.awt.List list1;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
