


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adam
 */
public class addConnectionFinal extends javax.swing.JFrame {
    
    int subnet, index, ethernetPort, hubIndex;
    /**
     * final part of add connection
     * allows user to specify last octet, it will also check to make sure the
     * entry is valid and available
     * Creates new form addConnectionFinal
     */
    public addConnectionFinal( int s, int i, int e, int h) {
        subnet = s;
        index = i;
        ethernetPort = e;
        hubIndex = h;
        //sets location at the previous forms
        this.setLocation(NetworkReader.p);
        this.setUndecorated(true);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setText("Specify last octet:");

        jLabel2.setText("IP: 192.168." + subnet + ".");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finishButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        addConnection s = new addConnection(index, ethernetPort); //opens form on button click
        s.setVisible(true); 
        super.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        int i;
        String s = jTextField1.getText();
        
        if (ipcheck(s)){ // if the specified value checks out
            
            i = Integer.parseInt(s); //converts entered value into integer
            
            NetworkReader.hubList.get(hubIndex).clientaddressList.add(i); //adds entered value to list of allocated addresses on corresponding hub
            NetworkReader.hubList.get(hubIndex).infList.add(NetworkReader.vmList.get(index).getName() + ".eth" + ethernetPort); //adds inf entry to the hub
            NetworkReader.vmList.get(index).addressList.remove(ethernetPort); //removes null address
            NetworkReader.vmList.get(index).addressList.add(ethernetPort, "\"192.168." + subnet + "." + i + "\""); //adds new address
            NetworkReader.vmList.get(index).subnetList.add(subnet); //adds addresses subnet to the vms list of connected subnets
            
            NetworkReader.drawConnections();
            
            NetworkReader.form.repaint();
            super.dispose();
            VMdata v = new VMdata(index); //opens form on button click
            v.setVisible(true);
        }
    }//GEN-LAST:event_finishButtonActionPerformed
    //checks the value input from the form,
    //calls appropriate error message if there is an error
    boolean ipcheck(java.lang.String s){
        int i = 0;
        int j = 0;
        String ErrMsg;
        
        try {
            i = Integer.parseInt(s);
        } catch(NumberFormatException e){ //if the value is not an integer
            ErrMsg = "ERROR: NEEDS INTEGER VALUE IN RANGE 1-255";
            Error error = new Error(ErrMsg);
            error.setVisible(true);
            jTextField1.setText(null);
            return false;
        }
        if ( i > 255 ){ //if the value is out of range
            ErrMsg = "ERROR: NEEDS INTEGER VALUE IN RANGE 1-255";
            Error error = new Error(ErrMsg);
            error.setVisible(true);
            jTextField1.setText(null);
            return false;
        }
        
        while ( j < NetworkReader.hubList.get(hubIndex).clientaddressList.size() ){//if the value specified is used by another address
            if (i == NetworkReader.hubList.get(hubIndex).clientaddressList.get(j)){
                ErrMsg = "ERROR: ADDRESS 192.168." + subnet + "." + i + " IS UNAVAILABLE";
                Error error = new Error(ErrMsg);
                error.setVisible(true);
                jTextField1.setText(null);
                return false;
            }
            j++;
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}