
import java.awt.MouseInfo;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * prompt that asks the user which way to proceed 
 * @author Adam
 */
public class Proceed extends javax.swing.JFrame {
    
    String errorMsg;
    String fileNameString;
    File fileNameFile;
    int useCase;
    //1 is load
    //2 is save
    //3 is clear
    /**
     * Creates new form Proceed
     */
    
    public Proceed(String e, String s, File f) {
        this.setUndecorated(true);
        NetworkReader.form.glassPane.setVisible(true); 
        //sets location at pointer
        this.setLocation(MouseInfo.getPointerInfo().getLocation());
        fileNameFile = f;
        fileNameString = s;
        errorMsg = e;
        initComponents();
        
        //determines use of form
        if ( f != null ){
            useCase = 2;
        }
        if ( s != null ){
            useCase = 1;
        }
        if ((s == null) && (f == null)){
            useCase = 3;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noButton = new javax.swing.JButton();
        yesButton = new javax.swing.JButton();
        proceedMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        noButton.setText("No");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        yesButton.setText("Yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        proceedMessage.setText(errorMsg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(yesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(noButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proceedMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(proceedMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noButton)
                    .addComponent(yesButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //logic for no button
    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        NetworkReader.form.glassPane.setVisible(false); 
        super.dispose();
    }//GEN-LAST:event_noButtonActionPerformed
    // logic for yes button
    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        if (useCase == 1){ //called from load
            try {
                load();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Proceed.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (useCase == 2){ //called from save
            try {
                save();
            } catch (IOException ex) {
                Logger.getLogger(Proceed.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (useCase == 3){ //called from clear
            clear();
        } 
        NetworkReader.form.glassPane.setVisible(false); 
        super.dispose();
    }//GEN-LAST:event_yesButtonActionPerformed

    //load cfg method
    private void load() throws FileNotFoundException{
            //clears workspace
            NetworkReader.clearNetwork();
            NetworkReader.connections.clearLines();
            NetworkReader.form.repaint();
            //loads new file
            readNetwork r = new readNetwork(fileNameString);
            NetworkReader.vmList = r.getvmList();
            NetworkReader.hubList = r.gethubList();
            NetworkReader.setIndex();
            NetworkReader.setNetworkConnections();
    }
    //saves the new file
    private void save() throws IOException{
        CreateCFG cfg = new CreateCFG(fileNameFile);
        cfg.writeToCFG();
    }
    //clears the workspace
    private void clear(){
        NetworkReader.clearNetwork();
        NetworkReader.connections.clearLines();
        NetworkReader.form.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton noButton;
    private javax.swing.JLabel proceedMessage;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
